# Generated by Django 4.0.3 on 2022-03-09 18:49

from django.db import migrations, models
import django.db.models.deletion
import movies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('movie_duration', models.DurationField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True)),
                ('movie_pic', models.ImageField(blank=True, upload_to=movies.models.path_and_rename, verbose_name='Movie Picture')),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateField(auto_now=True)),
                ('genres', models.CharField(blank=True, choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Thriller', 'Thriller')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('streetNo', models.CharField(blank=True, max_length=100)),
                ('landmark', models.CharField(blank=True, max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.city')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('09:00:00 - 12:00:00', '09:00:00 - 12:00:00'), ('12:00:00 - 03:00:00', '12:00:00 - 03:00:00'), ('03:00:00 - 06:00:00', '03:00:00 - 06:00:00'), ('06:00:00 - 09:00:00', '06:00:00 - 09:00:00')], max_length=30, null=True)),
                ('seat', models.CharField(max_length=100, null=True)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movies.movie')),
                ('theater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movies.theater')),
            ],
        ),
    ]
